//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iosKiosk.CodeproofService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authenticate", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class Authenticate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apikeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                if ((object.ReferenceEquals(this.apikeyField, value) != true)) {
                    this.apikeyField = value;
                    this.RaisePropertyChanged("apikey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custid {
            get {
                return this.custidField;
            }
            set {
                if ((object.ReferenceEquals(this.custidField, value) != true)) {
                    this.custidField = value;
                    this.RaisePropertyChanged("custid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPID", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class CPID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string devicetypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpid {
            get {
                return this.cpidField;
            }
            set {
                if ((object.ReferenceEquals(this.cpidField, value) != true)) {
                    this.cpidField = value;
                    this.RaisePropertyChanged("cpid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceidField, value) != true)) {
                    this.deviceidField = value;
                    this.RaisePropertyChanged("deviceid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string devicetype {
            get {
                return this.devicetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.devicetypeField, value) != true)) {
                    this.devicetypeField = value;
                    this.RaisePropertyChanged("devicetype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceProperty", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class DeviceProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatteryLifeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.NameValue[] DeviceInformationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalStorageFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalStorageUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.Infection[] InfectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.App[] InstalledApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.NameValue[] InstalledPoliciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.Profile[] InstalledProfilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalStorageFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalStorageUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastCheckinTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoryFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoryUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.App[] RunningApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.Process[] RunningProcessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iosKiosk.CodeproofService.App[] RunningServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenlockStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIdField, value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatteryLife {
            get {
                return this.BatteryLifeField;
            }
            set {
                if ((object.ReferenceEquals(this.BatteryLifeField, value) != true)) {
                    this.BatteryLifeField = value;
                    this.RaisePropertyChanged("BatteryLife");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.NameValue[] DeviceInformations {
            get {
                return this.DeviceInformationsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceInformationsField, value) != true)) {
                    this.DeviceInformationsField = value;
                    this.RaisePropertyChanged("DeviceInformations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalStorageFree {
            get {
                return this.ExternalStorageFreeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalStorageFreeField, value) != true)) {
                    this.ExternalStorageFreeField = value;
                    this.RaisePropertyChanged("ExternalStorageFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalStorageUsed {
            get {
                return this.ExternalStorageUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalStorageUsedField, value) != true)) {
                    this.ExternalStorageUsedField = value;
                    this.RaisePropertyChanged("ExternalStorageUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.Infection[] Infections {
            get {
                return this.InfectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.InfectionsField, value) != true)) {
                    this.InfectionsField = value;
                    this.RaisePropertyChanged("Infections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.App[] InstalledApplications {
            get {
                return this.InstalledApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstalledApplicationsField, value) != true)) {
                    this.InstalledApplicationsField = value;
                    this.RaisePropertyChanged("InstalledApplications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.NameValue[] InstalledPolicies {
            get {
                return this.InstalledPoliciesField;
            }
            set {
                if ((object.ReferenceEquals(this.InstalledPoliciesField, value) != true)) {
                    this.InstalledPoliciesField = value;
                    this.RaisePropertyChanged("InstalledPolicies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.Profile[] InstalledProfiles {
            get {
                return this.InstalledProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.InstalledProfilesField, value) != true)) {
                    this.InstalledProfilesField = value;
                    this.RaisePropertyChanged("InstalledProfiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalStorageFree {
            get {
                return this.InternalStorageFreeField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalStorageFreeField, value) != true)) {
                    this.InternalStorageFreeField = value;
                    this.RaisePropertyChanged("InternalStorageFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalStorageUsed {
            get {
                return this.InternalStorageUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalStorageUsedField, value) != true)) {
                    this.InternalStorageUsedField = value;
                    this.RaisePropertyChanged("InternalStorageUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastCheckinTime {
            get {
                return this.LastCheckinTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastCheckinTimeField, value) != true)) {
                    this.LastCheckinTimeField = value;
                    this.RaisePropertyChanged("LastCheckinTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemoryFree {
            get {
                return this.MemoryFreeField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoryFreeField, value) != true)) {
                    this.MemoryFreeField = value;
                    this.RaisePropertyChanged("MemoryFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemoryUsed {
            get {
                return this.MemoryUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoryUsedField, value) != true)) {
                    this.MemoryUsedField = value;
                    this.RaisePropertyChanged("MemoryUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSName {
            get {
                return this.OSNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OSNameField, value) != true)) {
                    this.OSNameField = value;
                    this.RaisePropertyChanged("OSName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSVersion {
            get {
                return this.OSVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.OSVersionField, value) != true)) {
                    this.OSVersionField = value;
                    this.RaisePropertyChanged("OSVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.App[] RunningApplications {
            get {
                return this.RunningApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningApplicationsField, value) != true)) {
                    this.RunningApplicationsField = value;
                    this.RaisePropertyChanged("RunningApplications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.Process[] RunningProcess {
            get {
                return this.RunningProcessField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningProcessField, value) != true)) {
                    this.RunningProcessField = value;
                    this.RaisePropertyChanged("RunningProcess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iosKiosk.CodeproofService.App[] RunningServices {
            get {
                return this.RunningServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningServicesField, value) != true)) {
                    this.RunningServicesField = value;
                    this.RaisePropertyChanged("RunningServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenlockStatus {
            get {
                return this.ScreenlockStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenlockStatusField, value) != true)) {
                    this.ScreenlockStatusField = value;
                    this.RaisePropertyChanged("ScreenlockStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameValue", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class NameValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infection", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class Infection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTakenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportedTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionTaken {
            get {
                return this.ActionTakenField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTakenField, value) != true)) {
                    this.ActionTakenField = value;
                    this.RaisePropertyChanged("ActionTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportedTime {
            get {
                return this.ReportedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportedTimeField, value) != true)) {
                    this.ReportedTimeField = value;
                    this.RaisePropertyChanged("ReportedTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="App", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class App : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceDirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportedTime {
            get {
                return this.ReportedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportedTimeField, value) != true)) {
                    this.ReportedTimeField = value;
                    this.RaisePropertyChanged("ReportedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDir {
            get {
                return this.SourceDirField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceDirField, value) != true)) {
                    this.SourceDirField = value;
                    this.RaisePropertyChanged("SourceDir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasRemovalPasscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsEncryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsManagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadOrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadRemovalDisallowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadUUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasRemovalPasscode {
            get {
                return this.HasRemovalPasscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HasRemovalPasscodeField, value) != true)) {
                    this.HasRemovalPasscodeField = value;
                    this.RaisePropertyChanged("HasRemovalPasscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsEncrypted {
            get {
                return this.IsEncryptedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsEncryptedField, value) != true)) {
                    this.IsEncryptedField = value;
                    this.RaisePropertyChanged("IsEncrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsManaged {
            get {
                return this.IsManagedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsManagedField, value) != true)) {
                    this.IsManagedField = value;
                    this.RaisePropertyChanged("IsManaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadDescription {
            get {
                return this.PayloadDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadDescriptionField, value) != true)) {
                    this.PayloadDescriptionField = value;
                    this.RaisePropertyChanged("PayloadDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadDisplayName {
            get {
                return this.PayloadDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadDisplayNameField, value) != true)) {
                    this.PayloadDisplayNameField = value;
                    this.RaisePropertyChanged("PayloadDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadIdentifier {
            get {
                return this.PayloadIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadIdentifierField, value) != true)) {
                    this.PayloadIdentifierField = value;
                    this.RaisePropertyChanged("PayloadIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadOrganization {
            get {
                return this.PayloadOrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadOrganizationField, value) != true)) {
                    this.PayloadOrganizationField = value;
                    this.RaisePropertyChanged("PayloadOrganization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadRemovalDisallowed {
            get {
                return this.PayloadRemovalDisallowedField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadRemovalDisallowedField, value) != true)) {
                    this.PayloadRemovalDisallowedField = value;
                    this.RaisePropertyChanged("PayloadRemovalDisallowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadUUID {
            get {
                return this.PayloadUUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadUUIDField, value) != true)) {
                    this.PayloadUUIDField = value;
                    this.RaisePropertyChanged("PayloadUUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadVersion {
            get {
                return this.PayloadVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadVersionField, value) != true)) {
                    this.PayloadVersionField = value;
                    this.RaisePropertyChanged("PayloadVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Process", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class Process : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessStartedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportedTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pid {
            get {
                return this.PidField;
            }
            set {
                if ((object.ReferenceEquals(this.PidField, value) != true)) {
                    this.PidField = value;
                    this.RaisePropertyChanged("Pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessStartedAt {
            get {
                return this.ProcessStartedAtField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessStartedAtField, value) != true)) {
                    this.ProcessStartedAtField = value;
                    this.RaisePropertyChanged("ProcessStartedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportedTime {
            get {
                return this.ReportedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportedTimeField, value) != true)) {
                    this.ReportedTimeField = value;
                    this.RaisePropertyChanged("ReportedTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandRecord", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class CommandRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIdField, value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Command {
            get {
                return this.CommandField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandField, value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandId {
            get {
                return this.CommandIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandIdField, value) != true)) {
                    this.CommandIdField = value;
                    this.RaisePropertyChanged("CommandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandName {
            get {
                return this.CommandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandNameField, value) != true)) {
                    this.CommandNameField = value;
                    this.RaisePropertyChanged("CommandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedOnField, value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedUserId {
            get {
                return this.CreatedUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedUserIdField, value) != true)) {
                    this.CreatedUserIdField = value;
                    this.RaisePropertyChanged("CreatedUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedOnField, value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Software", Namespace="http://schemas.datacontract.org/2004/07/Codeproof.External.Webservice")]
    [System.SerializableAttribute()]
    public partial class Software : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeployField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PkgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PkgUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustId {
            get {
                return this.CustIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustIdField, value) != true)) {
                    this.CustIdField = value;
                    this.RaisePropertyChanged("CustId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deploy {
            get {
                return this.DeployField;
            }
            set {
                if ((object.ReferenceEquals(this.DeployField, value) != true)) {
                    this.DeployField = value;
                    this.RaisePropertyChanged("Deploy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS {
            get {
                return this.OSField;
            }
            set {
                if ((object.ReferenceEquals(this.OSField, value) != true)) {
                    this.OSField = value;
                    this.RaisePropertyChanged("OS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PkgType {
            get {
                return this.PkgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PkgTypeField, value) != true)) {
                    this.PkgTypeField = value;
                    this.RaisePropertyChanged("PkgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PkgUrl {
            get {
                return this.PkgUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PkgUrlField, value) != true)) {
                    this.PkgUrlField = value;
                    this.RaisePropertyChanged("PkgUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedOnField, value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeproofService.ICodeproofService")]
    public interface ICodeproofService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/GetCPIDs", ReplyAction="http://tempuri.org/ICodeproofService/GetCPIDsResponse")]
        iosKiosk.CodeproofService.CPID[] GetCPIDs(iosKiosk.CodeproofService.Authenticate AuthObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/GetDeviceProperty", ReplyAction="http://tempuri.org/ICodeproofService/GetDevicePropertyResponse")]
        iosKiosk.CodeproofService.DeviceProperty GetDeviceProperty(iosKiosk.CodeproofService.Authenticate AuthObj, iosKiosk.CodeproofService.CPID cpid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/ExecuteCommand", ReplyAction="http://tempuri.org/ICodeproofService/ExecuteCommandResponse")]
        iosKiosk.CodeproofService.CommandRecord ExecuteCommand(iosKiosk.CodeproofService.Authenticate AuthObj, iosKiosk.CodeproofService.CPID cpid, iosKiosk.CodeproofService.CommandRecord cmdObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/AddPolicy", ReplyAction="http://tempuri.org/ICodeproofService/AddPolicyResponse")]
        string AddPolicy(iosKiosk.CodeproofService.Authenticate AuthObj, string nodename, string productid, string category, string name, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/PingDevice", ReplyAction="http://tempuri.org/ICodeproofService/PingDeviceResponse")]
        string PingDevice(iosKiosk.CodeproofService.Authenticate AuthObj, string nodeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/GetSoftwares", ReplyAction="http://tempuri.org/ICodeproofService/GetSoftwaresResponse")]
        iosKiosk.CodeproofService.Software[] GetSoftwares(iosKiosk.CodeproofService.Authenticate AuthObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/AddSoftware", ReplyAction="http://tempuri.org/ICodeproofService/AddSoftwareResponse")]
        string AddSoftware(iosKiosk.CodeproofService.Authenticate AuthObj, string name, string publisher, string os, string pkgurl, string pkgtype, string deploy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeproofService/UpdateSoftware", ReplyAction="http://tempuri.org/ICodeproofService/UpdateSoftwareResponse")]
        string UpdateSoftware(iosKiosk.CodeproofService.Authenticate AuthObj, string id, string name, string publisher, string os, string pkgurl, string pkgtype, string deploy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeproofServiceChannel : iosKiosk.CodeproofService.ICodeproofService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeproofServiceClient : System.ServiceModel.ClientBase<iosKiosk.CodeproofService.ICodeproofService>, iosKiosk.CodeproofService.ICodeproofService {
        
        public CodeproofServiceClient() {
        }
        
        public CodeproofServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeproofServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeproofServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeproofServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iosKiosk.CodeproofService.CPID[] GetCPIDs(iosKiosk.CodeproofService.Authenticate AuthObj) {
            return base.Channel.GetCPIDs(AuthObj);
        }
        
        public iosKiosk.CodeproofService.DeviceProperty GetDeviceProperty(iosKiosk.CodeproofService.Authenticate AuthObj, iosKiosk.CodeproofService.CPID cpid) {
            return base.Channel.GetDeviceProperty(AuthObj, cpid);
        }
        
        public iosKiosk.CodeproofService.CommandRecord ExecuteCommand(iosKiosk.CodeproofService.Authenticate AuthObj, iosKiosk.CodeproofService.CPID cpid, iosKiosk.CodeproofService.CommandRecord cmdObj) {
            return base.Channel.ExecuteCommand(AuthObj, cpid, cmdObj);
        }
        
        public string AddPolicy(iosKiosk.CodeproofService.Authenticate AuthObj, string nodename, string productid, string category, string name, string value) {
            return base.Channel.AddPolicy(AuthObj, nodename, productid, category, name, value);
        }
        
        public string PingDevice(iosKiosk.CodeproofService.Authenticate AuthObj, string nodeid) {
            return base.Channel.PingDevice(AuthObj, nodeid);
        }
        
        public iosKiosk.CodeproofService.Software[] GetSoftwares(iosKiosk.CodeproofService.Authenticate AuthObj) {
            return base.Channel.GetSoftwares(AuthObj);
        }
        
        public string AddSoftware(iosKiosk.CodeproofService.Authenticate AuthObj, string name, string publisher, string os, string pkgurl, string pkgtype, string deploy) {
            return base.Channel.AddSoftware(AuthObj, name, publisher, os, pkgurl, pkgtype, deploy);
        }
        
        public string UpdateSoftware(iosKiosk.CodeproofService.Authenticate AuthObj, string id, string name, string publisher, string os, string pkgurl, string pkgtype, string deploy) {
            return base.Channel.UpdateSoftware(AuthObj, id, name, publisher, os, pkgurl, pkgtype, deploy);
        }
    }
}
